import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { BrandLogo } from '../context/BrandingContext.jsx'

// Public, read-only progress report — no login needed. Shared by a student
// with their parent/guardian via a link from Analytics -> "Share with parent".
export default function ParentReport() {
  const { token } = useParams()
  const [data, setData] = useState(null)
  const [error, setError] = useState('')

  useEffect(() => {
    fetch(`/api/analytics/report/shared/${token}`)
      .then((r) => r.json().then((d) => ({ ok: r.ok, d })))
      .then(({ ok, d }) => { if (ok) setData(d); else setError(d.error || 'Report not found') })
      .catch(() => setError('Report load nahi ho paya.'))
  }, [token])

  const fmtDuration = (s) => {
    const h = Math.floor(s / 3600), m = Math.round((s % 3600) / 60)
    return h ? `${h}h ${m}m` : `${m}m`
  }

  if (error) return <div className="content" style={{ maxWidth: 600, textAlign: 'center', paddingTop: 60 }}><p className="muted">{error}</p></div>
  if (!data) return <div className="content" style={{ maxWidth: 600, textAlign: 'center', paddingTop: 60 }}><div className="spin" /></div>

  return (
    <div className="content" style={{ maxWidth: 720, padding: '28px 16px 60px' }}>
      <header className="row mb" style={{ justifyContent: 'space-between' }}>
        <BrandLogo />
        <button className="btn btn-ghost btn-sm" onClick={() => window.print()}>🖨️ Print</button>
      </header>

      <div className="card mb">
        <b style={{ fontSize: 20 }}>{data.name}'s Progress Report</b>
        <p className="tiny muted mt">{data.targetExam ? `Target exam: ${data.targetExam}` : ''}</p>
      </div>

      <div className="grid grid-3 mb">
        <div className="card" style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 28, fontWeight: 800 }}>{data.totalTests}</div>
          <p className="tiny muted">Tests completed</p>
        </div>
        <div className="card" style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 28, fontWeight: 800, color: data.avgAccuracy >= 60 ? 'var(--green)' : 'var(--amber)' }}>{data.avgAccuracy}%</div>
          <p className="tiny muted">Average accuracy</p>
        </div>
        <div className="card" style={{ textAlign: 'center' }}>
          <div style={{ fontSize: 28, fontWeight: 800 }}>{fmtDuration(data.totalTime)}</div>
          <p className="tiny muted">Total practice time</p>
        </div>
      </div>

      {data.weakTopics?.length > 0 && (
        <div className="card mb">
          <b className="small">Topics needing attention</b>
          <ul className="small mt" style={{ paddingLeft: 18, lineHeight: 1.9 }}>
            {data.weakTopics.map((t, i) => (
              <li key={i}>{t.topic_name} <span className="tiny muted">({t.subject_name} › {t.chapter_name}) — {Math.round((t.correct / t.attempts) * 100)}% accuracy</span></li>
            ))}
          </ul>
        </div>
      )}

      <div className="card">
        <b className="small">Recent tests</b>
        <table style={{ width: '100%', fontSize: 13, marginTop: 8, borderCollapse: 'collapse' }}>
          <tbody>
            {(data.recent || []).map((r, i) => (
              <tr key={i} style={{ borderBottom: '1px solid var(--border)' }}>
                <td style={{ padding: '6px 4px' }}>{r.title}</td>
                <td style={{ padding: '6px 4px', textAlign: 'right' }}>{r.accuracy}% accuracy</td>
                <td style={{ padding: '6px 4px', textAlign: 'right' }} className="tiny muted">{new Date(String(r.started_at).replace(' ', 'T') + 'Z').toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}</td>
              </tr>
            ))}
            {(!data.recent || data.recent.length === 0) && <tr><td className="tiny muted">No completed tests yet.</td></tr>}
          </tbody>
        </table>
      </div>

      <p className="tiny muted mt" style={{ textAlign: 'center' }}>Shared read-only progress report — generated by {data.name} from their Aisepadho account.</p>
    </div>
  )
}
